jwt:
  secret: YmFzZTY066GcIOyduOy9lOuUqeuQnCDslZTtmLgg7YKkIOq4uOqyjCDsjajso7zshLjsmpQ=  # = base64로 인코딩된 암호 키 길게 써주세요

  access:
    expiration : 80
    header: Authorization

  refresh:
    expiration: 90
    header: Authorization-refresh

